<?php 

// Создание папок
$folders = array(
array('/payments/hutkigrosh'),
array('/lib/payments/hutkigrosh'),
array('/lib/payments/hutkigrosh/esas'),
array('/lib/payments/hutkigrosh/esas/hutkigrosh'),
array('/lib/payments/hutkigrosh/esas/hutkigrosh/controllers'),
array('/lib/payments/hutkigrosh/esas/hutkigrosh/lang'),
array('/lib/payments/hutkigrosh/esas/hutkigrosh/wrappers'),
array('/lib/payments/hutkigrosh/vendor'),
array('/lib/payments/hutkigrosh/vendor/apache'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/assembly'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/changes'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/xml'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/logos'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/img'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/config'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/pattern'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/renderers'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/loggers'),
array('/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers'),
array('/lib/payments/hutkigrosh/vendor/composer'),
array('/lib/payments/hutkigrosh/vendor/esas'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/logs'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/utils'),
array('/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers'),
);

// Перемещение файлов имя => куда
$files = array(
array('/alfaclick.php', 'payments/hutkigrosh/alfaclick.php'),
array('/completion.php', 'payments/hutkigrosh/completion.php'),
array('/fail.php', 'payments/hutkigrosh/fail.php'),
array('/form.php', 'payments/hutkigrosh/form.php'),
array('/hutkigrosh.png', 'payments/hutkigrosh/hutkigrosh.png'),
array('/params.php', 'payments/hutkigrosh/params.php'),
array('/pay.php', 'payments/hutkigrosh/pay.php'),
array('/result.php', 'payments/hutkigrosh/result.php'),
array('/success.php', 'payments/hutkigrosh/success.php'),

array("/lib/payments/hutkigrosh/SimpleAutoloader.php", "lib/payments/hutkigrosh/SimpleAutoloader.php"),
array("/lib/payments/hutkigrosh/esas/hutkigrosh/controllers/ControllerNotifyBM.php", "lib/payments/hutkigrosh/esas/hutkigrosh/controllers/ControllerNotifyBM.php"),
array("/lib/payments/hutkigrosh/esas/hutkigrosh/controllers/ControllerWebpayFormBM.php", "lib/payments/hutkigrosh/esas/hutkigrosh/controllers/ControllerWebpayFormBM.php"),
array("/lib/payments/hutkigrosh/esas/hutkigrosh/lang/TranslatorBM.php", "lib/payments/hutkigrosh/esas/hutkigrosh/lang/TranslatorBM.php"),
array("/lib/payments/hutkigrosh/esas/hutkigrosh/wrappers/ConfigurationWrapperBM.php", "lib/payments/hutkigrosh/esas/hutkigrosh/wrappers/ConfigurationWrapperBM.php"),
array("/lib/payments/hutkigrosh/esas/hutkigrosh/wrappers/OrderProductWrapperBM.php", "lib/payments/hutkigrosh/esas/hutkigrosh/wrappers/OrderProductWrapperBM.php"),
array("/lib/payments/hutkigrosh/esas/hutkigrosh/wrappers/OrderWrapperBM.php", "lib/payments/hutkigrosh/esas/hutkigrosh/wrappers/OrderWrapperBM.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/CHANGELOG", "lib/payments/hutkigrosh/vendor/apache/log4php/CHANGELOG"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/INSTALL", "lib/payments/hutkigrosh/vendor/apache/log4php/INSTALL"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/LICENSE", "lib/payments/hutkigrosh/vendor/apache/log4php/LICENSE"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/NOTICE", "lib/payments/hutkigrosh/vendor/apache/log4php/NOTICE"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/README", "lib/payments/hutkigrosh/vendor/apache/log4php/README"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/apigen.neon", "lib/payments/hutkigrosh/vendor/apache/log4php/apigen.neon"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/build.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/build.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/composer.json", "lib/payments/hutkigrosh/vendor/apache/log4php/composer.json"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/doap_log4php.rdf", "lib/payments/hutkigrosh/vendor/apache/log4php/doap_log4php.rdf"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/package-config.php", "lib/payments/hutkigrosh/vendor/apache/log4php/package-config.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/package.php", "lib/payments/hutkigrosh/vendor/apache/log4php/package.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/phpdoc.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/phpdoc.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/phpunit.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/phpunit.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/pom.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/pom.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/assembly/src.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/assembly/src.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/changes/changes.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/changes/changes.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_console.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_console.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_dailyfile.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_dailyfile.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_echo.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_echo.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_file.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_file.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_firephp.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_firephp.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_mail.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_mail.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_mailevent.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_mailevent.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_mongodb.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_mongodb.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_null.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_null.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_pdo.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_pdo.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_php.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_php.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_rollingfile.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_rollingfile.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_socket.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_socket.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_socket_server.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_socket_server.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_syslog.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/appender_syslog.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/cache.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/cache.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/configurator_basic.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/configurator_basic.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/configurator_php.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/configurator_php.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/configurator_xml.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/configurator_xml.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_denyall.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_denyall.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_levelmatch.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_levelmatch.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_levelrange.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_levelrange.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_stringmatch.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/filter_stringmatch.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_html.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_html.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_pattern.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_pattern.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_simple.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_simple.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_ttcc.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_ttcc.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_xml.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/layout_xml.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/mdc.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/mdc.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/ndc.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/ndc.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/renderer_default.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/renderer_default.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/renderer_map.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/renderer_map.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/simple.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/php/simple.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_console.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_console.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_dailyfile.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_dailyfile.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_echo.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_echo.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_file.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_file.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_firephp.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_firephp.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_mail.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_mail.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_mailevent.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_mailevent.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_mongodb.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_mongodb.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_null.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_null.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_pdo.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_pdo.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_php.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_php.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_rollingfile.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_rollingfile.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_socket.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_socket.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_socket_server.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_socket_server.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_syslog.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/appender_syslog.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/cache.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/cache.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/configurator_php.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/configurator_php.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/configurator_xml.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/configurator_xml.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_denyall.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_denyall.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_levelmatch.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_levelmatch.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_levelrange.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_levelrange.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_stringmatch.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/filter_stringmatch.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_html.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_html.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_pattern.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_pattern.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_simple.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_simple.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_ttcc.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_ttcc.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_xml.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/layout_xml.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/mdc.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/mdc.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/ndc.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/ndc.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/renderer_default.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/renderer_default.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/renderer_map.properties", "lib/payments/hutkigrosh/vendor/apache/log4php/src/examples/resources/renderer_map.properties"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/Logger.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/Logger.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerAppender.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerAppender.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerAppenderPool.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerAppenderPool.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerAutoloader.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerAutoloader.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerConfigurable.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerConfigurable.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerConfigurator.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerConfigurator.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerException.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerException.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerFilter.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerFilter.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerHierarchy.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerHierarchy.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLayout.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLayout.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLevel.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLevel.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLocationInfo.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLocationInfo.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLoggingEvent.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerLoggingEvent.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerMDC.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerMDC.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerNDC.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerNDC.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerReflectionUtils.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerReflectionUtils.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerRoot.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerRoot.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerThrowableInformation.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/LoggerThrowableInformation.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderConsole.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderConsole.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderDailyFile.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderDailyFile.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderEcho.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderEcho.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderFile.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderFile.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderFirePHP.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderFirePHP.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderMail.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderMail.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderMailEvent.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderMailEvent.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderMongoDB.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderMongoDB.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderNull.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderNull.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderPDO.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderPDO.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderPhp.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderPhp.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderRollingFile.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderRollingFile.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderSocket.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderSocket.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderSyslog.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/appenders/LoggerAppenderSyslog.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapter.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapter.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterINI.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterINI.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterPHP.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterPHP.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterXML.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterXML.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfiguratorDefault.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/configurators/LoggerConfiguratorDefault.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterDenyAll.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterDenyAll.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterLevelMatch.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterLevelMatch.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterLevelRange.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterLevelRange.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterStringMatch.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/filters/LoggerFilterStringMatch.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerFormattingInfo.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerFormattingInfo.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerOptionConverter.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerOptionConverter.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerPatternParser.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerPatternParser.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerUtils.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/helpers/LoggerUtils.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutHtml.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutHtml.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutPattern.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutPattern.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutSerialized.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutSerialized.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutSimple.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutSimple.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutTTCC.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutTTCC.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutXml.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/layouts/LoggerLayoutXml.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverter.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverter.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterClass.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterClass.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterCookie.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterCookie.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterDate.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterDate.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterEnvironment.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterEnvironment.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterFile.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterFile.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLevel.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLevel.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLine.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLine.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLiteral.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLiteral.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLocation.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLocation.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLogger.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterLogger.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterMDC.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterMDC.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterMessage.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterMessage.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterMethod.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterMethod.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterNDC.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterNDC.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterNewLine.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterNewLine.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterProcess.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterProcess.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterRelative.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterRelative.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterRequest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterRequest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterServer.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterServer.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterSession.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterSession.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterSessionID.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterSessionID.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterSuperglobal.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterSuperglobal.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterThrowable.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/pattern/LoggerPatternConverterThrowable.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRenderer.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRenderer.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRendererDefault.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRendererDefault.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRendererException.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRendererException.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRendererMap.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/renderers/LoggerRendererMap.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/xml/log4php.dtd", "lib/payments/hutkigrosh/vendor/apache/log4php/src/main/php/xml/log4php.dtd"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/contributingpatches.apt", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/contributingpatches.apt"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/download.apt", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/download.apt"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/index.apt", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/index.apt"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/privacy-policy.apt", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/privacy-policy.apt"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/volunteering.apt", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/apt/volunteering.apt"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/cse.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/cse.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css/bootstrap.css", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css/bootstrap.css"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css/bootstrap.min.css", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css/bootstrap.min.css"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css/site.css", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/css/site.css"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/collapsed.gif", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/collapsed.gif"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/expanded.gif", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/expanded.gif"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/logos/ls-logo.jpg", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/logos/ls-logo.jpg"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/logos/maven-feather.png", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/images/logos/maven-feather.png"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/img/glyphicons-halflings-white.png", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/img/glyphicons-halflings-white.png"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/img/glyphicons-halflings.png", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/img/glyphicons-halflings.png"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/bootstrap.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/bootstrap.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/bootstrap.min.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/bootstrap.min.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/jquery.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/jquery.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/jquery.min.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/jquery.min.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/prettify.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/prettify.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/prettify.min.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/prettify.min.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/site.js", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/resources/js/site.js"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/site.vm", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/site.vm"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/site.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/site.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/changelog.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/changelog.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/console.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/console.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/daily-file.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/daily-file.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/echo.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/echo.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/file.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/file.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/firephp.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/firephp.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/mail-event.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/mail-event.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/mail.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/mail.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/mongodb.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/mongodb.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/null.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/null.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/pdo.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/pdo.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/php.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/php.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/rolling-file.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/rolling-file.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/socket.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/socket.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/syslog.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders/syslog.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/appenders.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/configuration.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/configuration.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/filters.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/filters.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/introduction.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/introduction.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/html.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/html.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/pattern.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/pattern.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/serialized.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/serialized.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/simple.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/simple.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/ttcc.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/ttcc.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/xml.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts/xml.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/layouts.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/loggers.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/loggers.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/renderers.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/docs/renderers.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/install.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/install.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/privacy.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/privacy.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/quickstart.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/site/xdoc/quickstart.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/config/phpunit_to_surefire.xslt", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/config/phpunit_to_surefire.xslt"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerAppenderPoolTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerAppenderPoolTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerAppenderTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerAppenderTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerConfiguratorTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerConfiguratorTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerExceptionTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerExceptionTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerFilterTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerFilterTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerHierarchyTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerHierarchyTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerLevelTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerLevelTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerLoggingEventTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerLoggingEventTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerMDCTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerMDCTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerNDCTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerNDCTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerReflectionUtilsTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerReflectionUtilsTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerRootTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerRootTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerTestHelper.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerTestHelper.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerThrowableInformationTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/LoggerThrowableInformationTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/README", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/README"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderConsoleTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderConsoleTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderDailyFileTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderDailyFileTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderEchoTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderEchoTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderFileTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderFileTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderFirephpTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderFirephpTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderMailEventTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderMailEventTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderMailTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderMailTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderMongoDBTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderMongoDBTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderNullTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderNullTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderPDOTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderPDOTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderPhpTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderPhpTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderRollingFileTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderRollingFileTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderSocketTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderSocketTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderSyslogTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/LoggerAppenderSyslogTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/socketServer.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/appenders/socketServer.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/bootstrap.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/bootstrap.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators/LoggerConfigurationAdapterINITest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators/LoggerConfigurationAdapterINITest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators/LoggerConfigurationAdapterPHPTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators/LoggerConfigurationAdapterPHPTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators/LoggerConfigurationAdapterXMLTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/configurators/LoggerConfigurationAdapterXMLTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterDenyAllTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterDenyAllTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterLevelMatchTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterLevelMatchTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterLevelRangeTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterLevelRangeTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterStringMatchTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/filters/LoggerFilterStringMatchTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers/LoggerOptionConverterTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers/LoggerOptionConverterTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers/LoggerPatternParserTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers/LoggerPatternParserTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers/LoggerUtilsTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/helpers/LoggerUtilsTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutHtmlTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutHtmlTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutPatternTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutPatternTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutSerializedTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutSerializedTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutSimpleTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutSimpleTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutTTCCTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutTTCCTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutXmlTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/layouts/LoggerLayoutXmlTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/pattern/LoggerPatternConverterTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/pattern/LoggerPatternConverterTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/renderers/LoggerRendererMapTest.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/php/renderers/LoggerRendererMapTest.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_invalid_appender_declaration_1.ini", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_invalid_appender_declaration_1.ini"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_invalid_appender_declaration_2.ini", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_invalid_appender_declaration_2.ini"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_invalid_syntax.ini", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_invalid_syntax.ini"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_valid.ini", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/config_valid.ini"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/values.ini", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/ini/values.ini"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_empty.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_empty.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_invalid_syntax.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_invalid_syntax.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_not_an_array.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_not_an_array.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_valid.php", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/php/config_valid.php"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_duplicate_logger.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_duplicate_logger.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_duplicate_renderer.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_duplicate_renderer.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_invalid_syntax.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_invalid_syntax.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_valid.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_valid.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_valid_underscore.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/adapters/xml/config_valid_underscore.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_appender_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_appender_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_filter_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_filter_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_filter_parameters.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_filter_parameters.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_layout_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_invalid_layout_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_no_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_no_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_no_layout_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_no_layout_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_not_existing_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_not_existing_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_not_existing_filter_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_not_existing_filter_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_not_existing_layout_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/appenders/config_not_existing_layout_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/config.yml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/config.yml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/config1.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/config1.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/loggers/config_invalid_additivity.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/loggers/config_invalid_additivity.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/loggers/config_not_existing_appenders.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/loggers/config_not_existing_appenders.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_default_renderer.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_default_renderer.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_invalid_rendering_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_invalid_rendering_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_no_rendered_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_no_rendered_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_no_rendering_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_no_rendering_class.xml"),
array("/lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_not_existing_rendering_class.xml", "lib/payments/hutkigrosh/vendor/apache/log4php/src/test/resources/configs/renderers/config_not_existing_rendering_class.xml"),
array("/lib/payments/hutkigrosh/vendor/autoload.php", "lib/payments/hutkigrosh/vendor/autoload.php"),
array("/lib/payments/hutkigrosh/vendor/composer/ClassLoader.php", "lib/payments/hutkigrosh/vendor/composer/ClassLoader.php"),
array("/lib/payments/hutkigrosh/vendor/composer/LICENSE", "lib/payments/hutkigrosh/vendor/composer/LICENSE"),
array("/lib/payments/hutkigrosh/vendor/composer/autoload_classmap.php", "lib/payments/hutkigrosh/vendor/composer/autoload_classmap.php"),
array("/lib/payments/hutkigrosh/vendor/composer/autoload_namespaces.php", "lib/payments/hutkigrosh/vendor/composer/autoload_namespaces.php"),
array("/lib/payments/hutkigrosh/vendor/composer/autoload_psr4.php", "lib/payments/hutkigrosh/vendor/composer/autoload_psr4.php"),
array("/lib/payments/hutkigrosh/vendor/composer/autoload_real.php", "lib/payments/hutkigrosh/vendor/composer/autoload_real.php"),
array("/lib/payments/hutkigrosh/vendor/composer/autoload_static.php", "lib/payments/hutkigrosh/vendor/composer/autoload_static.php"),
array("/lib/payments/hutkigrosh/vendor/composer/installed.json", "lib/payments/hutkigrosh/vendor/composer/installed.json"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/.gitignore", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/.gitignore"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/README.md", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/README.md"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/composer.json", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/composer.json"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/composer.lock", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/composer.lock"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/logs/.htaccess", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/logs/.htaccess"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/logs/hutkigrosh.log", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/logs/hutkigrosh.log"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/ConfigurationFields.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/ConfigurationFields.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/ViewFields.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/ViewFields.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/Controller.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/Controller.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerAddBill.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerAddBill.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerAlfaclick.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerAlfaclick.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerNotify.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerNotify.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerWebpayForm.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/controllers/ControllerWebpayForm.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/Locale.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/Locale.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/Translator.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/Translator.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/TranslatorImpl.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/TranslatorImpl.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/en_GB.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/en_GB.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/ru_RU.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/lang/ru_RU.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/AlfaclickRq.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/AlfaclickRq.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/AlfaclickRs.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/AlfaclickRs.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillInfoRq.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillInfoRq.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillInfoRs.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillInfoRs.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillNewRq.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillNewRq.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillNewRs.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillNewRs.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillProduct.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/BillProduct.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/HutkigroshProtocol.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/HutkigroshProtocol.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/HutkigroshRq.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/HutkigroshRq.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/HutkigroshRs.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/HutkigroshRs.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/LoginRq.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/LoginRq.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/LoginRs.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/LoginRs.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/WebPayRq.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/WebPayRq.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/WebPayRs.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/WebPayRs.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies/cookies-1585925769.txt", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies/cookies-1585925769.txt"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies/cookies-1585925805.txt", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies/cookies-1585925805.txt"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies/cookies-1585926032.txt", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/protocol/cookies/cookies-1585926032.txt"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/utils/Logger.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/utils/Logger.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/ConfigurationWrapper.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/ConfigurationWrapper.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/OrderProductWrapper.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/OrderProductWrapper.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/OrderWrapper.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/OrderWrapper.php"),
array("/lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/Wrapper.php", "lib/payments/hutkigrosh/vendor/esas/hutkigrosh-api-php/src/esas/hutkigrosh/wrappers/Wrapper.php"),
);

// Для установки в БД
$name = 'hutkigrosh';
$title = 'Хутки грош';
$enable = 0;
$type = 'system';
$desc = '<p>Оплата через сервсис Хутки грош.</p>';
$params = 'YTo4OntzOjc6ImVyaXBfaWQiO3M6MDoiIjtzOjU6ImxvZ2luIjtzOjA6IiI7czo0OiJwYXNzIjtzOjA6IiI7czo5OiJhbGZhY2xpY2siO2k6MDtzOjY6IndlYnBheSI7aTowO3M6Nzoic2FuZGJveCI7aTowO3M6MTI6ImFjY291bnRfdGltZSI7aTo3O3M6ODoiY3VycmVuY3kiO3M6MzoiQllOIjt9';
?>