name: Auto Deploy (non-main branches)

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.PATH }}

            git fetch origin

            git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}

            if git show-ref --verify --quiet refs/heads/${{ github.ref_name }}; then
              git checkout ${{ github.ref_name }}
            else
              git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
            fi

            git pull origin ${{ github.ref_name }}

            echo "✅ Successfully pulled and checked out branch ${{ github.ref_name }}"